development:
  host: localhost
  database: transformers_web_development

test:
  host: localhost
  database: transformers_web_test

staging:
  uri: <%= ENV['MONGOLAB_URI'] %>

production:
  uri: <%= ENV['MONGOLAB_URI'] %>