development:
  sessions:
    default:
      database: transformers_web_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: transformers_web_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default: 
      uri: <%= ENV['MONGOLAB_URI'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>